name: Deploy production to VPS

on:
  workflow_dispatch:
  push:
    branches:
      - 17.0

jobs:
  buildPushDeployToVps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          docker build -t freego555/odoo-test:latest .
          docker push freego555/odoo-test:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        env:
          POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          envs: POSTGRES_HOST,POSTGRES_PORT,POSTGRES_USER,POSTGRES_PASSWORD
          script: |
            docker image prune -af
            docker pull freego555/odoo-test:latest
            docker stop odoo-test
            docker rm odoo-test
            docker run \
              -d \
              --network=host \
              --name odoo-test \
              -e HOST="$POSTGRES_HOST" \
              -e PORT="$POSTGRES_PORT" \
              -e USER="$POSTGRES_USER" \
              -e PASSWORD="$POSTGRES_PASSWORD" \
              freego555/odoo-test:latest \
              -- -d odoo-test
