name: Build and push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - 17.0

jobs:
  buildPushToDockerHub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          docker build -t freego555/odoo-test:latest .
          docker push freego555/odoo-test:latest
