name: Build and push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - 17.0

jobs:
  buildPushToDockerHub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        run: |
          docker build -t freego555/odoo-test:latest .
          docker push freego555/odoo-test:latest

      - name: Trigger updating on a server
        id: updateDockerImageRequest
        uses: fjogeleit/http-request-action@v1.16.2
        with:
          url: ${{vars.VPS_UPDATE_URL}}
          method: 'GET'
          bearerToken: ${{secrets.VPS_UPDATE_TOKEN}}
          retry: ${{vars.VPS_UPDATE_RETRY_AMOUNT}}
          retryWait: ${{vars.VPS_UPDATE_RETRY_WAIT_MS}}

      - name: Show response of updating docker image request
        run: |
          echo ${{ steps.updateDockerImageRequest.outputs.response }}
